- include_role:
    name: mysql

- name: Creating mandatory (local) DB 
  include_role: 
    name: mysql
    tasks_from: db
  vars:
    mysql_db_user: "{{ gitea_db_user }}"
    mysql_db_pass: "{{ gitea_db_pass }}"
    mysql_db_name: "{{ gitea_db_name }}"
  register: mysql_created_db  
  tags:
    - db    

